### ISSUE TITLE
general todo

### ISSUE THREAD

**Issue by binex-dsk** [binex-dsk/OpenFitnessPal#1]
- [ ] Save/Load
- [ ] Cache used food items for offline use
- [ ] Recipe making
- [ ] Real journaling
  * [ ] edit existing entries
  * [ ] rename meals (globally)
 - [ ] Exercises
 - [ ] Real setup
 - [ ] Calorie needs calculations
 - [ ] Macro targets
 
Separate these out into issues at some point
