### ISSUE TITLE
general todo

### ISSUE THREAD

**Issue by crueter** [binex-dsk/OpenFitnessPal#2]
- [x] Save/Load
- [x] Cache used food items for offline use
- [x] Recipe making
- [x] Real journaling
  * [x] edit existing entries
  * [x] rename meals (globally)
 - [x] Exercises
 - [ ] Real setup
 - [x] Calorie needs calculations
 - [x] Macro targets
 
Separate these out into issues at some point
